@startuml
'https://plantuml.com/sequence-diagram
actor "User" as MD
title As a User i want to register a account

activate MD
MD -> ":System" : User types  required data in the UI
":System" --> ":System" : Gets data from User
":System" --> ":System" : Validates data(can not be null)
alt successful case - data is accepted
activate ":System"
":System" --> MD : Informs operation success
deactivate ":System"

end

alt failure case - data is not accepted
activate ":System"
":System" --> MD : Shows error message
deactivate ":System"

end
deactivate MD
@enduml