@startuml
'https://plantuml.com/sequence-diagram
actor "User" as MD
title As a User i want to add a ingredient to the Shopping cart
activate MD
MD -> ":System" : User clicks on  add ingredients
":System" --> ":System" : Gets the ingredient
":System" --> ":System" : Validates data(can not be null)
alt successful case - data is accepted
activate ":System"
":System" --> MD : Adds the  ingredient
deactivate ":System"

end

alt failure case - data is not accepted
activate ":System"
":System" --> MD : Shows error message
deactivate ":System"

end
deactivate MD
@enduml