@startuml
hide circle

class User{
Username
Hash
Password
}


class RecipeItem{
Id
Title
Image
}
class Ingredients{
Name
Image
Price
}

class FoodTrivia{
text
}


class CartItem{
Id
Name
Cost
}
User"1"--"1"FoodTrivia:can acess
User"1"--"1..*" CartItem:can access >
User "1" -- "1..*" RecipeItem: can access >
RecipeItem"1"--"1..*"Ingredients:has >
Ingredients"1..*" --right "1" CartItem: added to >

@enduml