@startuml
actor User as MD
title As a User I want to delete all ingredients from  the Shopping cart
activate MD

MD -> ":System" : User goes to ShoppingCart
activate ":System"

alt Successful case - Data is accepted
    ":System" --> ":System" : Data is processed
    ":System" --> MD : Deletes the  ingredients
else Failure case - Data is not accepted
    ":System" --> MD : Shows error message
end

deactivate ":System"
deactivate MD
@enduml
